# Generated by Django 5.0.1 on 2024-01-09 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filetagger', '0002_alter_tag_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessibleDirectory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=1024)),
            ],
        ),
    ]
