# Generated by Django 5.0.1 on 2024-01-12 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filetagger', '0003_accessibledirectory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='path',
            field=models.BooleanField(default=False),
        ),
    ]
